# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:/Users/Diego/Dropbox/VaBD/ProyectoSavingBrains/TMS-Optitracking/tms_view2\tms_viewer_gui.ui'
#
# Created: Thu Jul 24 15:28:02 2014
#      by: PyQt4 UI code generator 4.10.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(800, 600)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.splitter = QtGui.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.vtk_frame = QtGui.QFrame(self.splitter)
        self.vtk_frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.vtk_frame.setFrameShadow(QtGui.QFrame.Raised)
        self.vtk_frame.setObjectName(_fromUtf8("vtk_frame"))
        self.vtk_layout = QtGui.QVBoxLayout(self.vtk_frame)
        self.vtk_layout.setMargin(0)
        self.vtk_layout.setObjectName(_fromUtf8("vtk_layout"))
        self.groupBox = QtGui.QGroupBox(self.vtk_frame)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.groupBox)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.cones_rep = QtGui.QRadioButton(self.groupBox)
        self.cones_rep.setChecked(True)
        self.cones_rep.setObjectName(_fromUtf8("cones_rep"))
        self.horizontalLayout_2.addWidget(self.cones_rep)
        self.cyls_rep = QtGui.QRadioButton(self.groupBox)
        self.cyls_rep.setObjectName(_fromUtf8("cyls_rep"))
        self.horizontalLayout_2.addWidget(self.cyls_rep)
        self.lines_rep = QtGui.QRadioButton(self.groupBox)
        self.lines_rep.setObjectName(_fromUtf8("lines_rep"))
        self.horizontalLayout_2.addWidget(self.lines_rep)
        self.vtk_layout.addWidget(self.groupBox)
        self.block_view = QtGui.QFrame(self.splitter)
        self.block_view.setFrameShape(QtGui.QFrame.NoFrame)
        self.block_view.setFrameShadow(QtGui.QFrame.Raised)
        self.block_view.setObjectName(_fromUtf8("block_view"))
        self.verticalLayout = QtGui.QVBoxLayout(self.block_view)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.file_label = QtGui.QLabel(self.block_view)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.file_label.setFont(font)
        self.file_label.setObjectName(_fromUtf8("file_label"))
        self.verticalLayout.addWidget(self.file_label)
        self.date_label = QtGui.QLabel(self.block_view)
        self.date_label.setObjectName(_fromUtf8("date_label"))
        self.verticalLayout.addWidget(self.date_label)
        self.duration_label = QtGui.QLabel(self.block_view)
        self.duration_label.setObjectName(_fromUtf8("duration_label"))
        self.verticalLayout.addWidget(self.duration_label)
        self.label_4 = QtGui.QLabel(self.block_view)
        self.label_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.verticalLayout.addWidget(self.label_4)
        self.blocks_table = QtGui.QTableView(self.block_view)
        self.blocks_table.setAlternatingRowColors(True)
        self.blocks_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.blocks_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.blocks_table.setObjectName(_fromUtf8("blocks_table"))
        self.blocks_table.horizontalHeader().setStretchLastSection(True)
        self.blocks_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.blocks_table)
        self.frame = QtGui.QFrame(self.block_view)
        self.frame.setFrameShape(QtGui.QFrame.NoFrame)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.frame)
        self.horizontalLayout_3.setMargin(0)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.select_all = QtGui.QPushButton(self.frame)
        self.select_all.setObjectName(_fromUtf8("select_all"))
        self.horizontalLayout_3.addWidget(self.select_all)
        self.un_select_all = QtGui.QPushButton(self.frame)
        self.un_select_all.setObjectName(_fromUtf8("un_select_all"))
        self.horizontalLayout_3.addWidget(self.un_select_all)
        self.export_table = QtGui.QPushButton(self.frame)
        self.export_table.setObjectName(_fromUtf8("export_table"))
        self.horizontalLayout_3.addWidget(self.export_table)
        self.verticalLayout.addWidget(self.frame)
        self.label_5 = QtGui.QLabel(self.block_view)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.verticalLayout.addWidget(self.label_5)
        self.details_table = QtGui.QTableView(self.block_view)
        self.details_table.setAlternatingRowColors(True)
        self.details_table.setSelectionMode(QtGui.QAbstractItemView.SingleSelection)
        self.details_table.setSelectionBehavior(QtGui.QAbstractItemView.SelectRows)
        self.details_table.setObjectName(_fromUtf8("details_table"))
        self.details_table.horizontalHeader().setStretchLastSection(True)
        self.details_table.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.details_table)
        self.horizontalLayout.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuFile = QtGui.QMenu(self.menubar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionNew_Session = QtGui.QAction(MainWindow)
        self.actionNew_Session.setObjectName(_fromUtf8("actionNew_Session"))
        self.actionOpen_Session = QtGui.QAction(MainWindow)
        self.actionOpen_Session.setObjectName(_fromUtf8("actionOpen_Session"))
        self.actionSave_Session = QtGui.QAction(MainWindow)
        self.actionSave_Session.setObjectName(_fromUtf8("actionSave_Session"))
        self.actionQuit = QtGui.QAction(MainWindow)
        self.actionQuit.setObjectName(_fromUtf8("actionQuit"))
        self.menuFile.addAction(self.actionNew_Session)
        self.menuFile.addAction(self.actionOpen_Session)
        self.menuFile.addAction(self.actionSave_Session)
        self.menuFile.addAction(self.actionQuit)
        self.menubar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox.setTitle(_translate("MainWindow", "Representation", None))
        self.cones_rep.setText(_translate("MainWindow", "Cones", None))
        self.cyls_rep.setText(_translate("MainWindow", "Cylinders", None))
        self.lines_rep.setText(_translate("MainWindow", "Lines", None))
        self.file_label.setText(_translate("MainWindow", "<File>", None))
        self.date_label.setText(_translate("MainWindow", "<Date>", None))
        self.duration_label.setText(_translate("MainWindow", "<Duration>", None))
        self.label_4.setText(_translate("MainWindow", "Blocks", None))
        self.select_all.setText(_translate("MainWindow", "Select All", None))
        self.un_select_all.setText(_translate("MainWindow", "Unselect All", None))
        self.export_table.setText(_translate("MainWindow", "Export Table", None))
        self.label_5.setText(_translate("MainWindow", "Block details", None))
        self.menuFile.setTitle(_translate("MainWindow", "File", None))
        self.actionNew_Session.setText(_translate("MainWindow", "New Session", None))
        self.actionOpen_Session.setText(_translate("MainWindow", "Open Session", None))
        self.actionSave_Session.setText(_translate("MainWindow", "Save Session", None))
        self.actionQuit.setText(_translate("MainWindow", "Quit", None))

